#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LONGRUN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel)"

load_config_defaults() {
  local config_file="$1"
  local line key value
  [[ -f "${config_file}" ]] || return 0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    [[ "${line}" == *"="* ]] || continue
    key="${line%%=*}"
    key="${key#"${key%%[![:space:]]*}"}"
    key="${key%"${key##*[![:space:]]}"}"
    [[ "${key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    if [[ -z "${!key+x}" ]]; then
      value="${line#*=}"
      value="${value#"${value%%[![:space:]]*}"}"
      value="${value%"${value##*[![:space:]]}"}"
      if [[ "${#value}" -ge 2 && "${value:0:1}" == '"' && "${value: -1}" == '"' ]]; then
        value="${value:1:${#value}-2}"
      elif [[ "${#value}" -ge 2 && "${value:0:1}" == "'" && "${value: -1}" == "'" ]]; then
        value="${value:1:${#value}-2}"
      fi
      export "${key}=${value}"
    fi
  done <"${config_file}"
}

load_config_defaults "${LONGRUN_DIR}/config.env"
load_config_defaults "${LONGRUN_DIR}/config.defaults.env"

HERMES_BOARD="${HERMES_BOARD:-project-longrun}"
TASK_MAP="${LONGRUN_DIR}/runs/kanban-task-map.env"

log() {
  printf '[setup-kanban] %s\n' "$*" >&2
}

task_rows() {
  grep '^TASK|' "${LONGRUN_DIR}/task-queue.md" || true
}

task_var_name() {
  local key="$1"
  key="${key//-/_}"
  key="${key//./_}"
  printf 'HERMES_TASK_ID_%s' "${key}"
}

json_id() {
  python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])'
}

create_task() {
  local key="$1"
  local title="$2"
  local doc="$3"
  local body
  body="$(cat <<EOF
${key}

Canonical doc:
${doc}

Execution:
- Hermes is the supervisor only.
- Business edits must be performed by scripts/run-pipeline.sh through codex exec.
- Commit only after verifier returns PASS_COMMIT and checks pass.
EOF
)"

  log "creating task ${key}: ${title}"
  hermes kanban create "${key} ${title}" \
    --body "${body}" \
    --workspace "dir:${REPO_ROOT}" \
    --priority 50 \
    --idempotency-key "${HERMES_BOARD}-${key}" \
    --created-by "hermes-codex-longrun" \
    --max-retries 1 \
    --json | json_id
}

safe_link() {
  local parent="$1"
  local child="$2"
  [[ -n "${parent}" && -n "${child}" ]] || return 0
  hermes kanban link "${parent}" "${child}" >/dev/null 2>&1 || true
}

mkdir -p "${LONGRUN_DIR}/runs"

log "initializing Hermes kanban"
hermes kanban init

log "creating/switching board ${HERMES_BOARD}"
hermes kanban boards create "${HERMES_BOARD}" \
  --name "${HERMES_BOARD}" \
  --description "Hermes + Codex long-run board for ${REPO_ROOT}" \
  --switch

declare -A TASK_IDS
while IFS='|' read -r marker key title doc deps checks; do
  [[ "${marker}" == "TASK" && -n "${key}" ]] || continue
  TASK_IDS["${key}"]="$(create_task "${key}" "${title}" "${doc}")"
done < <(task_rows)

while IFS='|' read -r marker key title doc deps checks; do
  [[ "${marker}" == "TASK" && -n "${key}" ]] || continue
  IFS=',' read -ra dep_items <<<"${deps:-}"
  for dep in "${dep_items[@]}"; do
    dep="${dep//[[:space:]]/}"
    [[ -z "${dep}" ]] && continue
    safe_link "${TASK_IDS[${dep}]:-}" "${TASK_IDS[${key}]:-}"
  done
done < <(task_rows)

{
  printf '# Generated by setup-hermes-kanban.sh. This file is ignored by git.\n'
  printf 'HERMES_BOARD=%q\n' "${HERMES_BOARD}"
  for key in "${!TASK_IDS[@]}"; do
    printf '%s=%q\n' "$(task_var_name "${key}")" "${TASK_IDS[${key}]}"
  done
} >"${TASK_MAP}"

log "task map written to ${TASK_MAP}"
hermes kanban list
